"""Add missing columns to vulnerabilities

Revision ID: 09d73f1ba505
Revises: d92cedc045bb
Create Date: 2026-04-27 12:40:20.911497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d73f1ba505'
down_revision = 'd92cedc045bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feedback', sa.Column('analysis_id', sa.Integer(), nullable=True))
    op.add_column('feedback', sa.Column('scan_id', sa.Integer(), nullable=True))
    op.add_column('feedback', sa.Column('is_helpful', sa.Boolean(), nullable=True))
    op.add_column('feedback', sa.Column('analysis_type', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('conversation_id', sa.String(), nullable=True))
    op.add_column('feedback', sa.Column('feedback_data', sa.JSON(), nullable=True))
    op.add_column('feedback', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('feedback', 'vulnerability_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'feedback', 'scans', ['scan_id'], ['id'])
    op.add_column('vulnerabilities', sa.Column('remediation_commands', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulnerabilities', 'remediation_commands')
    op.drop_constraint(None, 'feedback', type_='foreignkey')
    op.alter_column('feedback', 'vulnerability_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('feedback', 'updated_at')
    op.drop_column('feedback', 'feedback_data')
    op.drop_column('feedback', 'conversation_id')
    op.drop_column('feedback', 'analysis_type')
    op.drop_column('feedback', 'is_helpful')
    op.drop_column('feedback', 'scan_id')
    op.drop_column('feedback', 'analysis_id')
    # ### end Alembic commands ###