"""Add user preference fields for theme and customization

Revision ID: 11184203572e
Revises: e185bb98fe4e
Create Date: 2025-07-11 20:50:26.681597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11184203572e'
down_revision = 'e185bb98fe4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('theme_preference', sa.String(), nullable=True))
    op.add_column('users', sa.Column('language_preference', sa.String(), nullable=True))
    op.add_column('users', sa.Column('timezone_preference', sa.String(), nullable=True))
    op.add_column('users', sa.Column('dashboard_layout', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dashboard_layout')
    op.drop_column('users', 'timezone_preference')
    op.drop_column('users', 'language_preference')
    op.drop_column('users', 'theme_preference')
    # ### end Alembic commands ###