"""Auto migration

Revision ID: 4aeb159d25ba
Revises: ff1ef8a636a3
Create Date: 2025-07-13 10:07:42.957738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aeb159d25ba'
down_revision = 'ff1ef8a636a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###