"""Add conversation memory persistence models

Revision ID: a8e0be7ae1d9
Revises: 11184203572e
Create Date: 2025-07-12 04:51:10.441719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e0be7ae1d9'
down_revision = '11184203572e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###