"""add language to reports

Revision ID: d83324f20bca
Revises: 09d73f1ba505
Create Date: 2026-04-28 16:33:22.407414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd83324f20bca'
down_revision = '09d73f1ba505'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('language', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'language')
    # ### end Alembic commands ###