"""Auto migration

Revision ID: d92cedc045bb
Revises: 4aeb159d25ba
Create Date: 2025-07-13 11:05:35.317883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd92cedc045bb'
down_revision = '4aeb159d25ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###