"""Add conversation memory models (fixed import)

Revision ID: ff1ef8a636a3
Revises: a8e0be7ae1d9
Create Date: 2025-07-12 04:53:31.381912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff1ef8a636a3'
down_revision = 'a8e0be7ae1d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('context_type', sa.String(), nullable=False),
    sa.Column('initial_prompt', sa.Text(), nullable=False),
    sa.Column('system_instructions', sa.Text(), nullable=True),
    sa.Column('suggested_questions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_templates_id'), 'conversation_templates', ['id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('context_type', sa.String(), nullable=True),
    sa.Column('context_metadata', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_context', 'conversations', ['context_type', 'is_active'], unique=False)
    op.create_index('idx_conversations_user_activity', 'conversations', ['user_id', 'last_activity_at'], unique=False)
    op.create_index(op.f('ix_conversations_conversation_id'), 'conversations', ['conversation_id'], unique=True)
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_table('user_preferences_ai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preferred_response_style', sa.String(), nullable=True),
    sa.Column('preferred_analysis_depth', sa.String(), nullable=True),
    sa.Column('preferred_explanation_level', sa.String(), nullable=True),
    sa.Column('enable_proactive_suggestions', sa.Boolean(), nullable=True),
    sa.Column('remember_context_across_sessions', sa.Boolean(), nullable=True),
    sa.Column('auto_generate_summaries', sa.Boolean(), nullable=True),
    sa.Column('enable_personalization', sa.Boolean(), nullable=True),
    sa.Column('share_anonymous_usage', sa.Boolean(), nullable=True),
    sa.Column('notify_on_new_features', sa.Boolean(), nullable=True),
    sa.Column('notify_on_security_insights', sa.Boolean(), nullable=True),
    sa.Column('preferences_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_preferences_user', 'user_preferences_ai', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_preferences_ai_id'), 'user_preferences_ai', ['id'], unique=False)
    op.create_table('conversation_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('key_topics', sa.Text(), nullable=True),
    sa.Column('user_preferences', sa.Text(), nullable=True),
    sa.Column('context_insights', sa.Text(), nullable=True),
    sa.Column('messages_summarized', sa.Integer(), nullable=False),
    sa.Column('summary_quality_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id')
    )
    op.create_index(op.f('ix_conversation_summaries_id'), 'conversation_summaries', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('context_data', sa.Text(), nullable=True),
    sa.Column('enhancement_data', sa.Text(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('was_helpful', sa.Boolean(), nullable=True),
    sa.Column('correction_provided', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('idx_messages_role_rating', 'messages', ['role', 'user_rating'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index('idx_messages_role_rating', table_name='messages')
    op.drop_index('idx_messages_conversation_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversation_summaries_id'), table_name='conversation_summaries')
    op.drop_table('conversation_summaries')
    op.drop_index(op.f('ix_user_preferences_ai_id'), table_name='user_preferences_ai')
    op.drop_index('idx_user_preferences_user', table_name='user_preferences_ai')
    op.drop_table('user_preferences_ai')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_conversation_id'), table_name='conversations')
    op.drop_index('idx_conversations_user_activity', table_name='conversations')
    op.drop_index('idx_conversations_context', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_conversation_templates_id'), table_name='conversation_templates')
    op.drop_table('conversation_templates')
    # ### end Alembic commands ###